
image:
  file: gitpod.Dockerfile

tasks:
  - init: cargo build --no-default-features --features server && cargo build --target wasm32-unknown-unknown
  - command: ./run.sh

github:
  prebuilds:
    master: true

vscode:
  extensions:
    - hbenl.test-adapter-converter
    - hbenl.vscode-test-explorer
